language: ruby
rvm:
- 2.7.2
cache: bundler
before_install:
- gem update --system
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
script:
- bundle exec rake spec
